nowcast_dates:
- '2024-10-09'
- '2024-10-16'
- '2024-10-23'
- '2024-10-30'
- '2024-11-06'
- '2024-11-13'
- '2024-11-20'
- '2024-11-27'
- '2024-12-04'
- '2024-12-11'
- '2024-12-18'
- '2024-12-25'
- '2025-01-01'
- '2025-01-08'
- '2025-01-15'
- '2025-01-22'
- '2025-01-29'
- '2025-02-05'
- '2025-02-12'
- '2025-02-19'
- '2025-02-26'
- '2025-03-05'
- '2025-03-12'
- '2025-03-19'
- '2025-03-26'
- '2025-04-02'
- '2025-04-09'
- '2025-04-16'
- '2025-04-23'
- '2025-04-30'
- '2025-05-07'
- '2025-05-14'
- '2025-05-21'
- '2025-05-28'
- '2025-06-04'
states_for_vis:
- CA
- OH
- IL
nowcast_date_for_vis: '2025-02-19'
quantiles_to_vis:
- 0.05
- 0.25
- 0.5
- 0.75
- 0.975
nowcast_bucket_name: covid-variant-nowcast-hub
hub_path: https://raw.githubusercontent.com/reichlab/variant-nowcast-hub/refs/heads/main/
clades_by_nowcast_date_dir: https://raw.githubusercontent.com/reichlab/variant-nowcast-hub/refs/heads/main/auxiliary-data/modeled-clades/
location_fp: https://raw.githubusercontent.com/cdcepi/FluSight-forecast-hub/refs/heads/main/auxiliary-data/locations.csv
scores_fp: https://raw.githubusercontent.com/reichlab/variant-nowcast-hub/refs/heads/main/auxiliary-data/scores/scores.tsv
raw_variant_data_ns_url: https://data.nextstrain.org/files/workflows/forecasts-ncov/open/nextstrain_clades/usa.tsv.gz
